spring.application.name=Flourish-Unit-2

spring.datasource.url=jdbc:mysql://localhost:3306/Flourish
spring.datasource.username=root
spring.datasource.password=IamROOT!
spring.jpa.hibernate.ddl-auto=update